-- BERITA MUDA INDONESIA V5 — complete Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  summary text,
  content_html text,
  url text unique not null,
  source_url text,
  image_url text,
  source text not null default 'ANTARA',
  author_name text,
  author_url text,
  category text not null default 'NASIONAL',
  tags text[] not null default '{}',
  reading_minutes integer not null default 1,
  content_source text not null default 'rss',
  content_available boolean not null default false,
  featured boolean not null default false,
  published_at timestamptz,
  views bigint not null default 0,
  likes bigint not null default 0,
  shares bigint not null default 0,
  status text not null default 'published' check(status in ('draft','published','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  video_url text not null,
  thumbnail_url text,
  source text not null default 'ADMIN',
  category text not null default 'VIDEO',
  author_name text,
  tags text[] not null default '{}',
  views bigint not null default 0,
  likes bigint not null default 0,
  shares bigint not null default 0,
  status text not null default 'draft' check(status in ('draft','published','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('admin','editor')),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('pageview','view','like','share','video_play','ad_impression','ad_click')),
  content_type text check (content_type in ('article','video','site','ad')),
  content_id uuid,
  path text,
  referrer text,
  session_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.trending_content (
  content_type text not null check (content_type in ('article','video')),
  content_id uuid not null,
  score numeric not null default 0,
  rank integer not null default 999,
  calculated_at timestamptz not null default now(),
  primary key(content_type, content_id)
);

create table if not exists public.ad_campaigns (
  id uuid primary key default gen_random_uuid(),
  advertiser_name text not null,
  title text not null,
  placement text not null check (placement in ('top','inline','sidebar','video')),
  image_url text,
  target_url text not null,
  alt_text text,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  active boolean not null default true,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists articles_category_idx on public.articles(category);
create index if not exists articles_published_idx on public.articles(published_at desc);
create index if not exists articles_featured_idx on public.articles(featured, published_at desc);
create index if not exists videos_created_idx on public.videos(created_at desc);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_content_idx on public.analytics_events(content_type, content_id, created_at desc);
create index if not exists trending_rank_idx on public.trending_content(rank, score desc);
create index if not exists ad_campaigns_active_idx on public.ad_campaigns(active, placement, starts_at, ends_at);

create or replace function public.is_editor() returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','editor'));
$$;

create or replace function public.increment_article_views(article_id uuid) returns void
language sql security definer set search_path=public as $$ update public.articles set views=views+1, updated_at=now() where id=article_id and status='published'; $$;
create or replace function public.increment_article_likes(article_id uuid) returns void
language sql security definer set search_path=public as $$ update public.articles set likes=likes+1, updated_at=now() where id=article_id and status='published'; $$;
create or replace function public.increment_article_shares(article_id uuid) returns void
language sql security definer set search_path=public as $$ update public.articles set shares=coalesce(shares,0)+1, updated_at=now() where id=article_id and status='published'; $$;
create or replace function public.increment_video_views(video_id uuid) returns void
language sql security definer set search_path=public as $$ update public.videos set views=views+1, updated_at=now() where id=video_id and status='published'; $$;
create or replace function public.increment_video_likes(video_id uuid) returns void
language sql security definer set search_path=public as $$ update public.videos set likes=likes+1, updated_at=now() where id=video_id and status='published'; $$;
create or replace function public.increment_video_shares(video_id uuid) returns void
language sql security definer set search_path=public as $$ update public.videos set shares=coalesce(shares,0)+1, updated_at=now() where id=video_id and status='published'; $$;
create or replace function public.increment_ad_impressions(campaign_id uuid) returns void
language sql security definer set search_path=public as $$ update public.ad_campaigns set impressions=impressions+1, updated_at=now() where id=campaign_id; $$;
create or replace function public.increment_ad_clicks(campaign_id uuid) returns void
language sql security definer set search_path=public as $$ update public.ad_campaigns set clicks=clicks+1, updated_at=now() where id=campaign_id; $$;

create or replace function public.rebuild_trending() returns void language plpgsql security definer set search_path=public as $$
begin
  truncate public.trending_content;
  insert into public.trending_content(content_type, content_id, score, rank)
  select content_type, content_id, score, row_number() over(order by score desc)::int
  from (
    select 'article'::text content_type, a.id content_id,
      (a.views * 1.0 + a.likes * 4.0 + a.shares * 7.0 + case when a.featured then 3 else 0 end) /
      greatest(1, extract(epoch from (now() - coalesce(a.published_at,a.created_at)))/3600.0 + 2) as score
    from public.articles a where a.status='published'
    union all
    select 'video'::text, v.id,
      (v.views * 1.0 + v.likes * 4.0 + v.shares * 7.0) /
      greatest(1, extract(epoch from (now() - v.created_at))/3600.0 + 2) as score
    from public.videos v where v.status='published'
  ) ranked;
end;
$$;

alter table public.articles enable row level security;
alter table public.videos enable row level security;
alter table public.profiles enable row level security;
alter table public.analytics_events enable row level security;
alter table public.trending_content enable row level security;
alter table public.ad_campaigns enable row level security;

drop policy if exists "public read published articles" on public.articles;
drop policy if exists "editor manage articles" on public.articles;
create policy "public read published articles" on public.articles for select using (status='published');
create policy "editor manage articles" on public.articles for all using (public.is_editor()) with check (public.is_editor());

drop policy if exists "public read published videos" on public.videos;
drop policy if exists "editor manage videos" on public.videos;
create policy "public read published videos" on public.videos for select using (status='published');
create policy "editor manage videos" on public.videos for all using (public.is_editor()) with check (public.is_editor());

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select using (auth.uid()=id);

drop policy if exists "public read trending" on public.trending_content;
create policy "public read trending" on public.trending_content for select using (true);

drop policy if exists "public read active ads" on public.ad_campaigns;
create policy "public read active ads" on public.ad_campaigns for select using (active=true and starts_at<=now() and (ends_at is null or ends_at>=now()));
drop policy if exists "editor manage ads" on public.ad_campaigns;
create policy "editor manage ads" on public.ad_campaigns for all using (public.is_editor()) with check (public.is_editor());

revoke all on function public.increment_article_views(uuid) from public;
revoke all on function public.increment_article_likes(uuid) from public;
revoke all on function public.increment_article_shares(uuid) from public;
revoke all on function public.increment_video_views(uuid) from public;
revoke all on function public.increment_video_likes(uuid) from public;
revoke all on function public.increment_video_shares(uuid) from public;
revoke all on function public.increment_ad_impressions(uuid) from public;
revoke all on function public.increment_ad_clicks(uuid) from public;
revoke all on function public.rebuild_trending() from public;
grant execute on function public.increment_article_views(uuid) to anon, authenticated;
grant execute on function public.increment_article_likes(uuid) to anon, authenticated;
grant execute on function public.increment_article_shares(uuid) to anon, authenticated;
grant execute on function public.increment_video_views(uuid) to anon, authenticated;
grant execute on function public.increment_video_likes(uuid) to anon, authenticated;
grant execute on function public.increment_video_shares(uuid) to anon, authenticated;
grant execute on function public.increment_ad_impressions(uuid) to anon, authenticated;
grant execute on function public.increment_ad_clicks(uuid) to anon, authenticated;
grant execute on function public.rebuild_trending() to service_role;

insert into storage.buckets (id,name,public) values ('videos','videos',false) on conflict (id) do nothing;
insert into storage.buckets (id,name,public) values ('thumbnails','thumbnails',true) on conflict (id) do nothing;
