-- BERITA MUDA INDONESIA V5.2 — Intelligent Revenue Engine
-- Run after migrations 001-005.

-- Affiliate inventory and click attribution.
create table if not exists public.affiliate_offers (
  id uuid primary key default gen_random_uuid(),
  partner_name text not null,
  title text not null,
  description text,
  target_url text not null,
  image_url text,
  category text,
  content_type text check (content_type in ('article','video','site')),
  content_id uuid,
  commission_model text not null default 'unknown' check (commission_model in ('cpa','cps','cpc','fixed','unknown')),
  estimated_commission numeric,
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  clicks bigint not null default 0,
  conversions bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists affiliate_offers_active_idx on public.affiliate_offers(active, category, starts_at, ends_at);

create table if not exists public.affiliate_clicks (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references public.affiliate_offers(id) on delete cascade,
  session_id text,
  content_type text,
  content_id uuid,
  created_at timestamptz not null default now()
);
create index if not exists affiliate_clicks_offer_idx on public.affiliate_clicks(offer_id, created_at desc);

-- Normalized revenue ledger. AdSense/partner revenue can be imported manually or via future connectors.
create table if not exists public.revenue_entries (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('adsense','direct_ad','sponsor','affiliate','video','subscription','other')),
  amount numeric not null default 0,
  currency text not null default 'IDR',
  occurred_at timestamptz not null default now(),
  content_type text check (content_type in ('article','video','site')),
  content_id uuid,
  campaign_id uuid references public.ad_campaigns(id) on delete set null,
  affiliate_offer_id uuid references public.affiliate_offers(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists revenue_entries_time_idx on public.revenue_entries(occurred_at desc);
create index if not exists revenue_entries_source_idx on public.revenue_entries(source, occurred_at desc);

-- Newsletter foundation; double-opt-in sending provider can be connected later.
create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text,
  categories text[] not null default '{}',
  status text not null default 'active' check (status in ('pending','active','unsubscribed')),
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Premium foundation. Payment provider is intentionally not hard-coded.
create table if not exists public.membership_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  price numeric not null default 0,
  currency text not null default 'IDR',
  interval text not null default 'monthly' check (interval in ('monthly','yearly','one_time')),
  active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.user_memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id uuid not null references public.membership_plans(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending','active','past_due','cancelled','expired')),
  starts_at timestamptz,
  ends_at timestamptz,
  provider text,
  provider_reference text,
  created_at timestamptz not null default now(),
  unique(user_id, plan_id)
);

-- Revenue intelligence view: a single source for the admin dashboard.
create or replace view public.revenue_summary as
select
  coalesce(source,'other') as source,
  currency,
  date_trunc('day', occurred_at) as day,
  sum(amount) as revenue,
  count(*) as entries
from public.revenue_entries
group by source, currency, date_trunc('day', occurred_at);

alter table public.affiliate_offers enable row level security;
alter table public.affiliate_clicks enable row level security;
alter table public.revenue_entries enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.membership_plans enable row level security;
alter table public.user_memberships enable row level security;

drop policy if exists "public read active affiliate offers" on public.affiliate_offers;
create policy "public read active affiliate offers" on public.affiliate_offers for select using (active=true and starts_at<=now() and (ends_at is null or ends_at>=now()));
drop policy if exists "editor manage affiliate offers" on public.affiliate_offers;
create policy "editor manage affiliate offers" on public.affiliate_offers for all using (public.is_editor()) with check (public.is_editor());
drop policy if exists "public read active membership plans" on public.membership_plans;
create policy "public read active membership plans" on public.membership_plans for select using (active=true);
drop policy if exists "editor manage membership plans" on public.membership_plans;
create policy "editor manage membership plans" on public.membership_plans for all using (public.is_editor()) with check (public.is_editor());

create or replace function public.increment_affiliate_click(p_offer_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.affiliate_offers set clicks=clicks+1, updated_at=now() where id=p_offer_id and active=true;
end;
$$;
revoke all on function public.increment_affiliate_click(uuid) from public;
grant execute on function public.increment_affiliate_click(uuid) to anon, authenticated, service_role;
