-- MUDA Indonesia V15 — Intelligent News Experience
create table if not exists public.reader_profiles (
  visitor_id text primary key,
  display_name text,
  locale text not null default 'id-ID',
  mode text not null default 'balanced',
  brief_time text not null default '07:00',
  alert_mode text not null default 'calm',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reader_follows (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  entity_type text not null check (entity_type in ('topic','source','location','author')),
  entity_key text not null,
  created_at timestamptz not null default now(),
  unique(visitor_id, entity_type, entity_key)
);

create table if not exists public.reader_saves (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  content_type text not null check (content_type in ('article','video')),
  content_id uuid not null,
  created_at timestamptz not null default now(),
  unique(visitor_id, content_type, content_id)
);

create table if not exists public.reader_feedback (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  content_type text not null check (content_type in ('article','video')),
  content_id uuid not null,
  feedback text not null check (feedback in ('more_like_this','less_like_this','not_interested','hide_source','useful')),
  created_at timestamptz not null default now()
);

create table if not exists public.story_brief_cache (
  content_id uuid primary key,
  brief text,
  key_points jsonb not null default '[]'::jsonb,
  source_count integer not null default 1,
  generated_by text not null default 'deterministic',
  confidence numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.reader_briefings (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  brief_date date not null default current_date,
  title text not null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique(visitor_id, brief_date)
);

create index if not exists reader_follows_visitor_idx on public.reader_follows(visitor_id, entity_type, entity_key);
create index if not exists reader_saves_visitor_idx on public.reader_saves(visitor_id, created_at desc);
create index if not exists reader_feedback_visitor_idx on public.reader_feedback(visitor_id, created_at desc);
create index if not exists reader_briefings_visitor_idx on public.reader_briefings(visitor_id, brief_date desc);

-- Safe helper: keep the store anonymous-by-default. Authentication can be layered later.
create or replace function public.upsert_reader_profile(p_visitor_id text, p_mode text default 'balanced', p_brief_time text default '07:00', p_alert_mode text default 'calm')
returns void language sql security definer set search_path=public as $$
  insert into public.reader_profiles(visitor_id, mode, brief_time, alert_mode, updated_at)
  values (p_visitor_id, coalesce(p_mode,'balanced'), coalesce(p_brief_time,'07:00'), coalesce(p_alert_mode,'calm'), now())
  on conflict(visitor_id) do update set mode=excluded.mode, brief_time=excluded.brief_time, alert_mode=excluded.alert_mode, updated_at=now();
$$;
